### ISSUE TITLE
Proxima fix in the Button component

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1873]
Hi

This fix is more likely for the Proxima font on Linux/macOS
https://github.com/brainly/style-guide/blob/0319fe5bcc422dfec3eaf19bfb5b886a671bcd47/src/components/buttons/_buttons.scss#L95-L99

But on the other hand, I think this fix kind of not useful with Proxima font on Windows

Before disabling `top` | After disabling
--- | ---
![image](https://user-images.githubusercontent.com/5789670/88260188-8d0c2700-cccc-11ea-91b1-1091806e22dc.png) | ![image](https://user-images.githubusercontent.com/5789670/88260238-a3b27e00-cccc-11ea-845f-58191b470678.png)

OS-specific solution for this issue is required.

**Comment by kubajasiolek** [comment]
@seahindeniz You may try something like this and use it with `top` set to 0:
```scss
  &::before {
    content: ' ';
    width: 0;
    font-family: Arial, Verdana, sans-serif;
  }
```
