### ISSUE TITLE
Having a single %component placeholder

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#75]
Given a nature of components we have, it seems we can base all our block on smth like that:

``` scss
%component {
  box-sizing: border-box;
  display: inline-block;
  position: relative;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

WDYT?
Do we need to add resets there as well?
